plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - Gemfile
    - 'vendor/**/*'
  NewCops: enable

# Layout

Layout/LineLength:
  Max: 130

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EmptyComment:
  Enabled: false

# Metrics

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Style

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# RSpec

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/NoExpectationExample:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
